import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[font]
size = 20.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.9
decorations = 'buttonless'
blur = true

[cursor]
style = "Block"
