#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config top_padding 0
bspc config window_gap 20

#bspc config border_width 30
bspc config border_width 0
#bspc config focused_border_color \#1f1f28
#bspc config active_border_color \#1f1f28
#bspc config normal_border_color \#1f1f28

bspc config borderless_monocle    true
bspc config single_monocle        true
bspc config gapless_monocle       true

bspc config focus_follows_pointer true

setxkbmap -layout us,ru -option grp:caps_toggle
feh --bg-scale $HOME/wallpapers/main.jpg
picom -b
$HOME/.config/polybar/launch.sh
